language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  - python: 3.5

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - pip install codecov

before_script:
  - python -V

script:
  - python setup.py install
  - py.test -v --cov=./

after_success:
  - codecov

notifications:
  email: false
